export enum Screens {
    DASHBOARD = "DASHBOARD",
    LOGIN = "LOGIN",
    SIGNUP = "SIGNUP",
    SPOTSELECT = "SPOTSELECT",
    REGIONS = "REGIONS",
    CLIMATE = "CLIMATE",
    PROFILE = "PROFILE"

  }